name: Development branches

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Check formatting
        run: yarn format:check

      - name: Build application
        run: yarn build

      - name: Run unit tests
        run: yarn test

      - name: Run end-to-end tests
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
          wait-on: 'http://localhost:3000'
