name: Development branches

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build application
        run: yarn build

      - name: Run unit tests
        run: yarn test:coverage

      - name: Run end-to-end test
        run: yarn cypress
