name: CI

on:
  push:
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install
        run: yarn
      
      - name: build
        run: yarn build

      - name: test
        run: yarn test:coverage && yarn jest-coverage-badges
        
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update coverage badges (Auto commit)

