name: Main branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build application
        run: yarn build

      - name: Run unit tests
        run: yarn test:badges

      - name: Run end-to-end test
        run: yarn cypress

      - name: Format all files with prettier
        run: yarn prettier --write .

      - name: Update screenshots for readme
        run: yarn cypress:screenshots

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto commit coverage, screenshots and prettier
