name: Main branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build application
        run: yarn build

      - name: Run unit tests (and update badges)
        run: yarn test:badges

      - name: Run end-to-end tests (and update screenshots)
        uses: cypress-io/github-action@v2
        with:
          start: yarn start

      - name: Format all files with prettier
        run: yarn prettier --write .

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto commit coverage, screenshots and prettier
